.Dd October 1, 2026
.Dt CWEL 1
.Os cwel.sh
.Sh NAME
.Nm cwel
.Nd open a link to Connor Welsh
.Sh SYNOPSIS
.Nm
.Op Fl -resume | -github | -linkedin | -email | -pgp
.Nm
.Fl -help
.Sh DESCRIPTION
.Nm
opens the link selected by its option in the user's web browser.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl -resume
Open the resume.
.It Fl -github
Open the GitHub profile.
.It Fl -linkedin
Open the LinkedIn profile.
.It Fl -email
Open the user's preferred e-mail composer in order to send a mail to
.Mt cwel@cwel.sh .
.It Fl -pgp
Display the OpenPGP public key.
.It Fl -help
Show command synopsis.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /resume
Contains the resume as an HTML page.
.It Pa /resume.pdf
Contains the resume as a PDF document.
.It Pa /cwel.asc
Contains the OpenPGP public key for
.Mt cwel@cwel.sh .
.It Pa ~/.config/
This directory is the default location for user-specific configuration.
Its contents are published at
.Lk https://github.com/cwelsys/dotfiles .
.El
.Sh SEE ALSO
.Xr cat 1 ,
.Xr cd 1 ,
.Xr ls 1 ,
.Xr man 1
.Sh AUTHORS
.An Connor Welsh Aq Mt cwel@cwel.sh
