.Dd October 1, 2026
.Dt CWEL 1
.Os cwel.sh
.Sh NAME
.Nm cwel
.Nd Connor Welsh, software developer
.Sh SYNOPSIS
.Nm
.Op Fl -resume
.Op Fl -github
.Op Fl -email
.Sh DESCRIPTION
Builds web software that works with a keyboard and a screen reader,
and the tooling around it.
Currently a contract developer at the Blind Institute of Technology.
.Pp
Before that: Salesforce administration, project management,
technical recruiting, and a few years running his own shop.
.Sh FILES
.Bl -tag -width /resume.pdf
.It Pa /resume
the long version
.It Pa /resume.pdf
the same, for sending
.It Pa /cwel.asc
OpenPGP public key
.El
.Sh SEE ALSO
.Lk https://github.com/cwelsys ,
.Mt cwel@cwel.sh
.Sh AUTHORS
.An Connor Welsh Aq Mt cwel@cwel.sh
