var logos = {
  Chrome: `⠀⠀⠀⠀⠀⠀<span style="color:#de3428">⢀⡠⡰⡰⡪⡪⡪⡎⣖⢲</span><span style="color:#e8463a">⢤⢠</span>⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀<span style="color:#de3428">⡠⡪⡪⡪⡪⡺⡸⡱⡕⡇⡧⡣⣣</span><span style="color:#e8463a">⢳⢹⢲⢠</span>⠀⠀⠀⠀
⠀⠀<span style="color:#de3428">⢠⢪⢪⡪⡪⡺⡸⡪⡺⡸⡜⡎⡮⡺⡸</span><span style="color:#e8463a">⡪⡣⡳⡱⡕⡄</span>⠀⠀
⠀<span style="color:#259745">⣰</span><span style="color:#de3428">⢱⢱⢱⢱⢹⢸⢸</span><span style="color:#b74b53">⣪</span><span style="color:#f2d991">⣾⣾⣾⣾⣾⣾</span><span style="color:#f9b821">⣳⣟⣾⢽⣞⣷⣻</span><span style="color:#fcc41e">⣆</span>⠀
<span style="color:#259745">⢠⢗⡽</span><span style="color:#de3428">⡜⡜⡎⡎</span><span style="color:#f2d991">⣾⣿</span><span style="color:#1c76da">⢻⡹⡜⡼⡸⣍⢟</span><span style="color:#f2d991">⣿⣾</span><span style="color:#fcc41e">⡽⣯⡷⣟⣾⢾⡄</span>
<span style="color:#259745">⣜⢗⡽⡵</span><span style="color:#b74b53">⡕</span><span style="color:#de3428">⡕</span><span style="color:#b74b53">⣽</span><span style="color:#f2d991">⣿</span><span style="color:#1c76da">⢕⢇⡗⣝⢼⢱⢕⢇⣏</span><span style="color:#f2d991">⣿⣟</span><span style="color:#fcc41e">⣷⣟⣯⢿⡽⣧</span>
<span style="color:#259745">⢮⡳⣝⢮⡫</span><span style="color:#b74b53">⡎</span><span style="color:#f2d991">⣿⣗</span><span style="color:#1c76da">⡕⡧⣫⢪⢎⢧⡫⢮⢲</span><span style="color:#f2d991">⢽⣿</span><span style="color:#fcc41e">⣳⣟⣾⣻⣽⢷</span>
<span style="color:#259745">⢳⢝⡮⣳⢝⣝</span><span style="color:#61ae74">⢾</span><span style="color:#f2d991">⣿</span><span style="color:#1c76da">⡜⡮⣪⡣⣏⢮⡪⡳⣕</span><span style="color:#f2d991">⣿⣿</span><span style="color:#fcc41e">⣽⢾⡯⣟⣾⠯</span>
<span style="color:#259745">⠨⡳⣝⢮⡳⣕⢗</span><span style="color:#61ae74">⡽</span><span style="color:#f2d991">⣿</span><span style="color:#1c76da">⣮⣎⢮⡪⣎⢮⣳</span><span style="color:#f2d991">⣿⣟</span><span style="color:#fcc41e">⣷⣻⣽⣻⣽⢯⠃</span>
⠀<span style="color:#259745">⠹⣜⢵⢝⢮⡳⣝⢮</span><span style="color:#61ae74">⢻</span><span style="color:#f2d991">⡻⡿⡿⡿</span><span style="color:#61ae74">⡟⣟</span><span style="color:#f9b821">⣵</span><span style="color:#fcc41e">⢿⣞⡿⣞⡿⣾⠋</span>⠀
⠀⠀<span style="color:#259745">⠈⢗⢽⡱⡳⡵⡹⣕⣝⢮⡺⡪⣞</span><span style="color:#f9b821">⢾</span><span style="color:#fcc41e">⣽⢯⣿⢽⡿⡽⠃</span>⠀⠀
⠀⠀⠀<span style="color:#259745">⠈⠑⠽⣱⢝⣝⢼⢜⢮⢎⢯</span><span style="color:#f9b821">⢾</span><span style="color:#fcc41e">⣻⣽⢿⡽⡯⠋</span>⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀<span style="color:#259745">⠈⠑⠱⠳⡹⣪⢳</span><span style="color:#f9b821">⣻</span><span style="color:#fcc41e">⢟⠯⠟⠙⠁</span>⠀⠀⠀⠀⠀⠀`,
  Edge: `⠀⠀⠀⠀⠀⠀<span style="color:#2fc4dc">⢀⡤⣴⣲⣳⢯⢯⣻⡺⣖⣦</span><span style="color:#32c798">⣤⣀</span>⠀⠀⠀⠀⠀⠀
⠀⠀⠀<span style="color:#2fc4dc">⢀⣠⡾⣽⢽⣺⣞⢾⢽⣻⣺⢽⣳⣳</span><span style="color:#32c798">⢗⡿⣽</span><span style="color:#3bcf82">⢦</span><span style="color:#52de7b">⡄</span>⠀⠀⠀
⠀⠀<span style="color:#2fc4dc">⣠⢾⣺⢽⣺⡽⣞⡾⣽⣻⣺⣺⢽⣺⣞</span><span style="color:#32c798">⡯⡿</span><span style="color:#3bcf82">⣽</span><span style="color:#52de7b">⣫⡿⣵</span>⠀⠀
⠀<span style="color:#2fc4dc">⣰⢯</span><span style="color:#24acd8">⢻</span><span style="color:#0a81d0">⢪⢫</span><span style="color:#057ace">⡪⣎⢮</span><span style="color:#0a81d0">⡪⣣⢳</span><span style="color:#24acd8">⢳</span><span style="color:#2fc4dc">⢯⣻⣺</span><span style="color:#32c798">⣺⢽⢯</span><span style="color:#3bcf82">⡷</span><span style="color:#52de7b">⣯⢿⡽⣷⡀</span>
<span style="color:#2fc4dc">⢰</span><span style="color:#0a81d0">⢝</span><span style="color:#057ace">⢜⡎</span><span style="color:#0a81d0">⣗⡳⣝⢼⠵⣝⢮⡳⢕</span><span style="color:#0b5ca5">⢝</span><span style="color:#24acd8">⢞</span><span style="color:#2fc4dc">⣵</span><span style="color:#32c798">⢯⢿⢽</span><span style="color:#3bcf82">⡽</span><span style="color:#52de7b">⣽⢯⡿⣽⣖</span>
<span style="color:#0a81d0">⡪</span><span style="color:#057ace">⡎</span><span style="color:#0a81d0">⣗⢽⡸⣪⢮⡳⣝</span><span style="color:#057ace">⠎</span><span style="color:#0a81d0">⠁</span>⠀⠀⠀<span style="color:#0b5ca5">⠈</span><span style="color:#32c798">⢳⣻⢽</span><span style="color:#3bcf82">⣫⢿</span><span style="color:#52de7b">⢽⢯⢿⡽⣾</span>
<span style="color:#0a81d0">⡎⣗⢕⢧⡫⣺⢪⡺</span><span style="color:#0e4f92">⡰⡁</span>⠀⠀⠀⠀⠀<span style="color:#32c798">⢨⢯⢯</span><span style="color:#3bcf82">⢯⣟⣽</span><span style="color:#52de7b">⣻⢽⢯⠗</span>
<span style="color:#0a81d0">⢪</span><span style="color:#057ace">⢎</span><span style="color:#0a81d0">⢗⢵⡹⣜⢵</span><span style="color:#0e4f92">⠱⣘</span><span style="color:#0b5ca5">⢄</span>⠀⠀⠀⠀<span style="color:#3bcf82">⢀⡾⡽⣽⡳⡯⡾⡽</span><span style="color:#52de7b">⡽⠋</span>⠀
<span style="color:#057ace">⠨⣪⢳⢕</span><span style="color:#0a81d0">⢧⢳</span><span style="color:#0b5ca5">⡱</span><span style="color:#0e4f92">⡱⡡</span><span style="color:#0b5ca5">⡣⡢</span>⠀⠀⠀⠀<span style="color:#3bcf82">⠉⠛⠪⠫⠫⠋⠋</span>⠀⠀⠀
⠀<span style="color:#057ace">⠘⡎⡧⡳⡕⡇</span><span style="color:#0e4f92">⡎⢎</span><span style="color:#0b5ca5">⢎⢎⢕</span><span style="color:#0e4f92">⢤</span><span style="color:#0b5ca5">⢀</span>⠀⠀⠀⠀⠀⠀⠀⠀<span style="color:#0e4f92">⡀</span>⠀⠀
⠀⠀<span style="color:#057ace">⠘⢎⢞⢎⢧</span><span style="color:#0b5ca5">⢣</span><span style="color:#0e4f92">⠣⡣</span><span style="color:#0b5ca5">⡱</span><span style="color:#0e4f92">⡱⡱⡑⡍⡎⢆⢆⢆⢲⢘⠜⠈</span>⠀⠀
⠀⠀⠀⠀<span style="color:#057ace">⠙⢜⢕⢧</span><span style="color:#0b5ca5">⢣</span><span style="color:#0e4f92">⢣⠣⡣⡪⡪⡪⡪⡪⡊⡎⡪⠊</span>⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀<span style="color:#057ace">⠈⠑⠙⠎⢮</span><span style="color:#0b5ca5">⢪⡸⡨</span><span style="color:#0e4f92">⡢⠣⠊⠊</span>⠀⠀⠀⠀⠀⠀⠀`,
  Firefox: `⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀<span style="color:#ffe547">⣠⣾⣦</span>⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀<span style="color:#ffe547">⣴⣿⣷⣿⣧⡄</span>⠀⠀⠀⠀⠀⠀
⠀⠀⠀<span style="color:#faa537">⢀⣴⡂</span>⠀<span style="color:#faa537">⣀⡄</span>⠀⠀⠀<span style="color:#fed043">⢸</span><span style="color:#ffe547">⣿⣽⣾⣷⡿⣟⣦</span>⠀<span style="color:#ffe547">⡀</span>⠀⠀⠀
⠀⠀<span style="color:#fe732f">⡰⣝</span><span style="color:#faa537">⣗⡧⣼⣳⡅</span><span style="color:#9641bb">⢀⢠⢄</span><span style="color:#9e64b9">⢏⢗</span><span style="color:#faa537">⢟</span><span style="color:#fed043">⢷⣟⣿⢿⡿</span><span style="color:#ffe547">⣷⣘⣦</span>⠀⠀
⠀<span style="color:#fe732f">⢰⢽⢵⣳⣫</span><span style="color:#faa537">⣗⢷⣻⢾</span><span style="color:#9e64b9">⣜</span><span style="color:#9641bb">⢎⢧⢫⡪</span><span style="color:#9e64b9">⢶⣭</span><span style="color:#fed043">⣻⣟⣿⣻⡷</span><span style="color:#ffe547">⣿⣆</span>⠀
⠀<span style="color:#fe732f">⡳⣝⢞</span><span style="color:#faa537">⢾⣺⣾⣻⣾⣽⢾⣻</span><span style="color:#9e64b9">⢎</span><span style="color:#9641bb">⢧⢫⡪</span><span style="color:#9e64b9">⡺</span><span style="color:#fed043">⡿⣞⣯⡿⣽</span><span style="color:#ffe547">⡿⣷</span>⠀
⠀<span style="color:#fb4942">⡯⣪⡫</span><span style="color:#fe732f">⣳⣓⢗</span><span style="color:#faa537">⡟</span><span style="color:#9e64b9">⡎⡮⡳⡵⡝</span><span style="color:#9641bb">⣎⢇⢇⢇</span><span style="color:#faa537">⢟</span><span style="color:#fed043">⣿</span><span style="color:#faa537">⣳⢿</span><span style="color:#fed043">⡽⣟</span><span style="color:#ffe547">⣿</span>⠄
⠀<span style="color:#f62956">⢣</span><span style="color:#fb4942">⢇⢯⡪⣎</span><span style="color:#fe732f">⠯</span><span style="color:#9e64b9">⣇</span><span style="color:#9641bb">⢇⢏⢞⢜⢮⢺⢸⢱⢡</span><span style="color:#faa537">⣻⡽⣞⣽⣻</span><span style="color:#fed043">⡯⣿</span>⠀
⠀<span style="color:#f62956">⠘⡜</span><span style="color:#fb4942">⣕⢵⢱⢝⢮</span><span style="color:#cc1c8c">⡪</span><span style="color:#9641bb">⡪⡪⡣⡣⡣⡣⡱</span><span style="color:#fb4942">⣺</span><span style="color:#fe732f">⣪⢯</span><span style="color:#faa537">⣗⣟⡾⣝⠇</span>⠀
⠀⠀<span style="color:#f62956">⠑⡕⡕⡵⡹⡸</span><span style="color:#fb4942">⡜⡵</span><span style="color:#f62956">⡱⡕⡮⡪</span><span style="color:#fb4942">⣎⢯⢺⢜</span><span style="color:#fe732f">⡵⣳⢳⢝⠞</span>⠀⠀
⠀⠀⠀<span style="color:#f62956">⠈⢎⢪⢪⢣⡣⡳⡹⡸⡪⡺⡸⡜</span><span style="color:#fb4942">⡎⡇</span><span style="color:#f62956">⡏⡮</span><span style="color:#fb4942">⡪⠃</span>⠀⠀⠀
⠀⠀⠀⠀⠀<span style="color:#f62956">⠈⠪⢢⠣⡣⡣⡓⡕⡝⡜⡜⡜⡜⠜⠈</span>⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀<span style="color:#cc1c8c">⠈</span><span style="color:#f62956">⠈⠂⠃⠃⠊⠊⠈</span>⠀⠀⠀⠀⠀⠀⠀⠀⠀`,
  Safari: `⠀⠀⠀⠀⠀⠀⠀<span style="color:#f7f7f7">⢀⣠⣤</span><span style="color:#f6f5f4">⣤⣶⣶⣶⣶⣤</span><span style="color:#f7f7f7">⣤⣄⡀</span>⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀<span style="color:#f7f7f7">⢀</span><span style="color:#f6f5f4">⣤⣾</span><span style="color:#c3dcf4">⣿⣿</span><span style="color:#4ba3fb">⣿⠟</span><span style="color:#1d8dfe">⢻⣿⠛⢻</span><span style="color:#4ba3fb">⡿⠿</span><span style="color:#c3dcf4">⣿⣿</span><span style="color:#f6f5f4">⣷</span><span style="color:#f7f7f7">⣤</span><span style="color:#f3f1f1">⡀</span>⠀⠀⠀⠀
⠀⠀⠀<span style="color:#f7f7f7">⣴</span><span style="color:#f3f1f1">⣿</span><span style="color:#c3dcf4">⣿</span><span style="color:#1d8dfe">⢿</span><span style="color:#198bff">⣿⡁⢻⡇⠈⠿</span>⠀<span style="color:#198bff">⠿⠃</span><span style="color:#188cfe">⣠</span><span style="color:#1d8dfe">⡿</span><span style="color:#4ba3fb">⠛</span><span style="color:#c04c60">⢻⣿⣿</span><span style="color:#f3f1f1">⣦</span>⠀⠀⠀
⠀<span style="color:#f6f5f4">⢀⣾</span><span style="color:#c3dcf4">⣿</span><span style="color:#1d8dfe">⣿</span><span style="color:#198bff">⣷⣄⠙⠓</span>⠀⠀⠀⠀⠀⠀⠀<span style="color:#c04c60">⠉</span>⠀<span style="color:#c04c60">⣴⠟⠉</span><span style="color:#4ba3fb">⣿</span><span style="color:#c3dcf4">⣿</span><span style="color:#f6f5f4">⣷⡀</span>⠀
⠀<span style="color:#f7f7f7">⣾</span><span style="color:#c3dcf4">⣿</span><span style="color:#1d8dfe">⣿</span><span style="color:#198bff">⣥⡈⠙</span>⠀⠀⠀⠀⠀⠀⠀⠀<span style="color:#c04c60">⣠⣴⠟</span>⠀<span style="color:#c04c60">⢰</span><span style="color:#1d8dfe">⠾</span><span style="color:#198bff">⠛</span><span style="color:#1d8dfe">⢻</span><span style="color:#c3dcf4">⣿</span><span style="color:#f7f7f7">⣷</span>⠀
<span style="color:#f6f5f4">⢠⣿</span><span style="color:#4ba3fb">⣿</span><span style="color:#198bff">⣉⠉⠛</span>⠀⠀⠀⠀⠀<span style="color:#188cfe">⢀</span><span style="color:#4ba3fb">⣠</span><span style="color:#c04c60">⣴⣿⣿⠋</span>⠀⠀⠀<span style="color:#198bff">⢰⠶⠿</span><span style="color:#4ba3fb">⣿</span><span style="color:#f6f5f4">⣿⡄</span>
<span style="color:#f7f7f7">⢸</span><span style="color:#f3f1f1">⣿</span><span style="color:#1d8dfe">⣿</span><span style="color:#198bff">⠛⠛⠃</span>⠀⠀⠀⠀<span style="color:#c3dcf4">⢀</span><span style="color:#4ba3fb">⣾</span><span style="color:#198bff">⣿</span><span style="color:#188cfe">⣿</span><span style="color:#4ba3fb">⡿</span><span style="color:#c04c60">⠁</span>⠀⠀⠀⠀<span style="color:#198bff">⢠⣤⣤</span><span style="color:#1d8dfe">⣿</span><span style="color:#f3f1f1">⣿</span><span style="color:#f7f7f7">⡇</span>
<span style="color:#f6f5f4">⠘⣿</span><span style="color:#4ba3fb">⣿</span><span style="color:#198bff">⣶⠾⠇</span>⠀⠀⠀<span style="color:#f3f1f1">⣰⣿⣿</span><span style="color:#c3dcf4">⠟</span><span style="color:#4ba3fb">⠋</span><span style="color:#198bff">⠁</span>⠀⠀⠀⠀⠀<span style="color:#198bff">⣄⣈⢉</span><span style="color:#4ba3fb">⣿</span><span style="color:#f6f5f4">⣿⠃</span>
⠀<span style="color:#f7f7f7">⢿</span><span style="color:#c3dcf4">⣿</span><span style="color:#1d8dfe">⣧</span><span style="color:#198bff">⣤</span><span style="color:#1d8dfe">⡶</span><span style="color:#c3dcf4">⠇</span><span style="color:#f3f1f1">⢀⣴⠟⠋⠁</span>⠀⠀⠀⠀⠀⠀⠀<span style="color:#198bff">⣄⡈⢛</span><span style="color:#1d8dfe">⣿</span><span style="color:#c3dcf4">⣿</span><span style="color:#f7f7f7">⡿</span>⠀
⠀<span style="color:#f6f5f4">⠈⢿</span><span style="color:#c3dcf4">⣿</span><span style="color:#4ba3fb">⣿</span><span style="color:#c3dcf4">⣀</span><span style="color:#f3f1f1">⣴⠟⢁</span><span style="color:#c3dcf4">⣀</span>⠀⠀⠀⠀⠀⠀⠀<span style="color:#198bff">⢤⣄⠙⢿</span><span style="color:#1d8dfe">⣿</span><span style="color:#c3dcf4">⣿</span><span style="color:#f6f5f4">⡿⠁</span>⠀
⠀⠀⠀<span style="color:#f6f5f4">⠻</span><span style="color:#f3f1f1">⣿⣿</span><span style="color:#c3dcf4">⣧</span><span style="color:#4ba3fb">⣤</span><span style="color:#1d8dfe">⣾</span><span style="color:#188cfe">⠋</span><span style="color:#198bff">⢰⡶</span>⠀<span style="color:#198bff">⣶⡀⢹⣦⢈⣿</span><span style="color:#1d8dfe">⣷</span><span style="color:#c3dcf4">⣿</span><span style="color:#f3f1f1">⣿</span><span style="color:#f7f7f7">⠟</span>⠀⠀⠀
⠀⠀⠀⠀<span style="color:#f7f7f7">⠈⠛</span><span style="color:#f6f5f4">⢿</span><span style="color:#c3dcf4">⣿⣿</span><span style="color:#4ba3fb">⣶⣿</span><span style="color:#1d8dfe">⣧⣤⣿⣧</span><span style="color:#4ba3fb">⣴⣿</span><span style="color:#c3dcf4">⣿⣿</span><span style="color:#f6f5f4">⡿⠛</span><span style="color:#f7f7f7">⠁</span>⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀<span style="color:#f7f7f7">⠈⠙⠛</span><span style="color:#f6f5f4">⠛⠿⠿⠿⠿⠛</span><span style="color:#f7f7f7">⠛⠋⠁</span>⠀⠀⠀⠀⠀⠀⠀`,
};
